name: Maven Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"  # Poll SCM every minute
  workflow_dispatch:  # Allow manual triggering of workflow with input
    inputs:
      GOAL:
        description: 'Choose the Maven Goal'
        required: true
        default: 'clean package'
        type: choice
        options:
          - 'package'
          - 'clean package'
          - 'validate'
          - 'install'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'  # Use Zulu OpenJDK (could be 'adoptopenjdk' as well)

      - name: Run Maven Build
        run: mvn ${{ github.event.inputs.GOAL || 'clean package' }}  # Default to 'install' if GOAL is not provided

      - name: Archive WAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gameoflife.war
          path: '**/target/gameoflife.war'

      - name: Publish JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: '**/surefire-reports/TEST-*.xml'

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # Trigger this step regardless of the build outcome

    steps:
      - name: Send success/failure email notification
        uses: dawidd6/action-send-mail@v4
        with:
          from: vijay1399@gmail.com
          to: vijaymetgud9@gmail.com
          subject: "${{ job.status }}: Build Status - ${{ github.repository }}"
          body: |
            Hi, this GitHub Actions job has completed.
            Build Status: ${{ job.status }}
            Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          server_address: smtp.gmail.com    # Gmail SMTP server address
          server_port: 587                  # Port 587 for TLS
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}  # Store your Gmail username in GitHub Secrets
          password: ${{ secrets.SMTP_PASSWORD }}  # Store your Gmail app-specific password in GitHub Secrets



