name: Maven Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"  # Polls SCM every minute

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'

      - name: Run Maven Build
        run: mvn ${{ github.event.inputs.GOAL }}  # Access parameterized GOAL here if needed

      - name: Archive WAR artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gameoflife.war
          path: '**/target/gameoflife.war'

      - name: Publish JUnit test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: '**/surefire-reports/TEST-*.xml'

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()

    steps:
      - name: Send success/failure email notification
        run: |
          subject="${{ job.status }}: ${GITHUB_JOB} has completed"
          body="Hi, this GitHub Actions job \n Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          # Use an email sending service or GitHub Actions SMTP email action here
          echo "Sending email... (you can integrate email service here)"
          echo "Subject: $subject"
          echo "Body: $body"
